name: "deploy-to-render"
description: "Trigger a deploy on Render for a given service using the Render API"
inputs:
  service_id:
    description: "Render service id (e.g. srv-xxxxxxxx)"
    required: true
  api_key:
    description: "Render API key"
    required: true
  wait_for_completion:
    description: "Whether to poll until deploy finishes (true/false)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Trigger deploy via Render API
      shell: bash
      run: |
        set -euo pipefail
        SERVICE_ID="${{ inputs.service_id }}"
        API_KEY="${{ inputs.api_key }}"
        echo "Triggering deploy for service $SERVICE_ID"
        HTTP_OUT=$(mktemp)
        HTTP_CODE=$(curl -s -o "$HTTP_OUT" -w "%{http_code}" -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
          -H "Authorization: Bearer ${API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{}')
        if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
          echo "Failed to trigger deploy (HTTP $HTTP_CODE)"
          cat "$HTTP_OUT"
          exit 1
        fi
        echo "Deploy triggered (HTTP $HTTP_CODE)"
        cat "$HTTP_OUT"
        echo "service-id=$SERVICE_ID" >> $GITHUB_OUTPUT
        echo "http-code=$HTTP_CODE" >> $GITHUB_OUTPUT
        WAIT="${{ inputs.wait_for_completion }}"
        if [ "$WAIT" = "true" ]; then
          echo "Waiting for deploy completion..."
          while true; do
            sleep 5
            LATEST=$(curl -s -H "Authorization: Bearer ${API_KEY}" "https://api.render.com/v1/services/${SERVICE_ID}/deploys?limit=1")
            status=$(python - <<PY
import sys, json
j=json.load(sys.stdin)
if isinstance(j, list) and len(j)>0:
    print(j[0].get('status',''))
else:
    print('')
PY
<<<"$LATEST")
            echo "Deploy status: $status"
            if [ "$status" = "success" ]; then
              echo "Deploy succeeded"
              break
            elif [ "$status" = "failed" ]; then
              echo "Deploy failed"
              echo "$LATEST"
              exit 1
            fi
          done
        fi
    - name: Done
      run: echo "Render deploy step finished"
